links:
  rails_tutorial:
    home_page: http://www.railstutorial.org/
    help_page: http://www.railstutorial.org/help
    help_book: http://www.railstutorial.org/book
    news: https://news.learnenough.com
    author: https://www.michaelhartl.com
    screencast: https://www.learnenough.com/courses
    ruby_on_rails: https://rubyonrails.org/
    contact_page: https://www.railstutorial.org/contact
  gravatar: https://secure.gravatar.com/avatar/

validations:
  name:
    max_length: 50
  email:
    max_length: 225
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
